CC = g++ 

INC = ./include
SRC = ./source
BUD = ./build

CFLAGS = -g -Wall -I${INC} -std=c++11

SOURCES = $(wildcard ${SRC}/*.cpp)

# SOURCES += ${MAIN_FILE}
# $(info $(SOURCES))

# patsubset format, target, needed files
OBJS = $(patsubst %.cpp,${BUD}/%.o,$(notdir ${SOURCES}))

# $(info $(OBJS))
TARGET = NES

# $@: target $^: all dependent files $<: the first dependent file
${TARGET}: ${OBJS}
	$(CC) ${OBJS} -o $@  

${BUD}/%.o:${SRC}/%.cpp
	$(CC) $(CFLAGS) -o $@ -c $<

.PHONY:clean

clean:
	find $(BUD) -name *.o -exec rm -rf {} \;
	# rm -rf main.o
	rm -rf ${TARGET}
