CC = clang++ 

INC = ./include
SFML_INC = /usr/local/Cellar/sfml/2.5.1_1/include
SRC = ./source
BUD = ./build

CFLAGS = -g -Wall -I${INC} -I${SFML_INC} -std=c++11
LDFLAGS = -L/usr/local/Cellar/sfml/2.5.1_1/lib -lsfml-graphics -lsfml-window -lsfml-system

SOURCES = $(wildcard ${SRC}/*.cpp)

# SOURCES += ${MAIN_FILE}
# $(info $(SOURCES))

# patsubset format, target, needed files
OBJS = $(patsubst %.cpp,${BUD}/%.o,$(notdir ${SOURCES}))

# $(info $(OBJS))
TARGET = run

# $@: target $^: all dependent files $<: the first dependent file
${TARGET}: ${OBJS}
	$(CC) ${OBJS} -o $@ $(LDFLAGS)

${BUD}/%.o:${SRC}/%.cpp
	$(CC) $(CFLAGS) -o $@ -c $<

.PHONY:clean

clean:
	find $(BUD) -name *.o -exec rm -rf {} \;
	# rm -rf main.o
	rm -rf ${TARGET}
